---
- name: "update apt packages"
  become: true
  apt:
    update_cache: yes
- name: "Upgradet apt Packages."
  become: true
  apt:
    upgrade: yes
- name: "Install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "tar", "gzip"]
    state: latest
    update_cache: yes
- name: "Install tar, gzip, zip"
  become:  true
  shell: apt-get -y install tar gzip
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
    #- name: "Create ~/web"
    #become: true
    #file:
    #path: web
    #state: directory
    #mode: '0755'
    #- name: "Copy Files"
    #become: true
    #copy:
    #src: artifact.tar.gz
    #dest: ./web
    #backup: true
    #remote_src: yes
    #- name: "Change working directory"
    #become: true
    #shell: cd web
- name: "Unzip backend.tar.gz"
  become: true
  shell: tar -xvzf artifact.tar.gz
- name: "Executing"
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
