---
- name: "update apt packages"
  become: true
  apt:
    update_cache: yes
- name: "Upgradet apt Packages."
  become: true
  apt:
    upgrade: yes
- name: "Install dependencies"
  become: true
  apt:
    name: ["nodejs", "npm", "tar", "gzip"]
    state: latest
    update_cache: yes
- name:
  become:  true
  shell: apt-get -y install tar gzip
- name: "Install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
- name: "Print WD"
  become: true
  shell: pwd
    #- name: "update yum packages"
    #become: true
    #yum:
    #update-cache: true
    #- name: "upgrade packages"
    #become: true
    #yum:
    #name: "*"
    #state: latest
- name: "Print working directory"
  become: true
  shell: pwd
- name: "Create ~/web"
  become: true
  file:
    path: web
    state: directory
    mode: '0755'
- name: "Copy Files"
  become: true
  copy:
    src: backend.tar.gz
    dest: ./web
    backup: true
    remote_src: yes
- name: "Change working directory"
  become: true
  shell: cd web
- name: "Unzip backend.tar.gz"
  become: true
  unarchive:
    src: ./web/backend.tar.gz
    dest: ./web
    backup: true
    remote_src: true
- name: "Executing"
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
