version: 2.1

orbs:
  slack: circleci/slack@4.1

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps: 
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - run:
          name: Build Front-End
          command: |
            cd frontend
            npm install
            npm run build
  build-backend: 
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - run:
          name: Build Back-End
          command: |
            cd backend
            npm install
            npm run build
  test-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - run:
          name: Test Front-End
          command: |
            cd frontend
            npm install
            npm run test
  test-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - run:
          name: Test Back-End
          command: |
            cd backend
            npm install
            npm run test
  scan-frontend:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - run:
          name: Scan Front-End
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical  --force
            npm audit --audit-level=critical
  scan-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: basic_success_1
      - run:
          name: Scan Back-End
          command: |
            cd frontend
            npm install
            npm audit fix --audit-level=critical --force
            npm audit --audit-level=critical
workflows:
  default:
    jobs:
      - build-frontend:
          context: CircleBot
      - build-backend:
          context: CircleBot
      - test-frontend:
          context: CircleBot
          requires: [build-frontend]
      - test-backend:
          context: CircleBot
          requires: [build-backend]
      - scan-frontend:
          context: CircleBot
          requires: [build-frontend]
      - scan-backend:
          context: CircleBot
          requires: [build-backend]
